// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Http = require("http");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Model$Reclock = require("../Model.bs.js");

var payload = /* record */[
  /* time */1.0,
  /* locale : EN */2
];

function handler(_, res) {
  console.log("Sending you stuff...");
  var x = Model$Reclock.Payload[/* to_t */1](Model$Reclock.Json[/* parse */1](Model$Reclock.Json[/* stringify */0](Model$Reclock.Payload[/* from_t */0](payload))));
  console.log(Caml_obj.caml_equal(x, payload));
  res.write(Model$Reclock.Json[/* stringify */0](Model$Reclock.Payload[/* from_t */0](payload)));
  res.end();
  console.log("Done!");
  return /* () */0;
}

Http.createServer(handler).listen(2112, (function () {
        console.log("Running...");
        return /* () */0;
      }));

exports.payload = payload;
exports.handler = handler;
/*  Not a pure module */
