// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as Http from "http";

Http.createServer((function (_, _$1) {
          return /* () */0;
        })).listen(2112, (function (prim) {
        console.log(prim);
        return /* () */0;
      }));

export {
  
}
/*  Not a pure module */
