// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as Http from "http";
import * as Model$Reclock from "../Model.bs.js";

var payload = /* record */[
  /* time */1,
  /* lang : En */0
];

function handler(_, res) {
  console.log("Sending you stuff...");
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.write(Model$Reclock.Json[/* stringify */0](payload));
  res.end();
  console.log("Done! Yes!");
  return /* () */0;
}

Http.createServer(handler).listen(2112, (function () {
        console.log("Running...");
        return /* () */0;
      }));

export {
  payload ,
  handler ,
  
}
/*  Not a pure module */
