// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/lib/es6/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";
import * as Model$Reclock from "../Model.bs.js";
import * as Component1$Reclock from "./Component1.bs.js";
import * as Component2$Reclock from "./Component2.bs.js";

var payload = /* record */[
  /* time */1.0,
  /* locale : EN */2
];

console.log(Model$Reclock.Json[/* stringify */0](Model$Reclock.Payload[/* from_t */0](payload)));

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Component1$Reclock.make("Hello!", /* array */[])), "index1");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Component2$Reclock.make("Hello!", /* array */[])), "index2");

export {
  payload ,
  
}
/*  Not a pure module */
