// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/lib/es6/src/ReactDOMRe.js";
import * as App$Reclock from "./App.bs.js";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";
import * as Model$Reclock from "../Model.bs.js";

var payload = /* record */[
  /* time */1,
  /* lang : En */0
];

console.log(Model$Reclock.Json[/* stringify */0](payload));

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, App$Reclock.make(/* array */[])), "app");

export {
  payload ,
  
}
/*  Not a pure module */
