// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE


function locale_to_string(param) {
  switch (param) {
    case 0 : 
        return "DE";
    case 1 : 
        return "ES";
    case 2 : 
        return "EN";
    
  }
}

function locale_of_string(param) {
  switch (param) {
    case "DE" : 
        return /* DE */0;
    case "ES" : 
        return /* ES */1;
    default:
      return /* EN */2;
  }
}

function stringify(prim) {
  return JSON.stringify(prim);
}

function parse(prim) {
  return JSON.parse(prim);
}

var Json = /* module */[
  /* stringify */stringify,
  /* parse */parse
];

function from_t(t) {
  return {
          time: t[/* time */0],
          locale: locale_to_string(t[/* locale */1])
        };
}

function to_t(payload) {
  return /* record */[
          /* time */payload.time,
          /* locale */locale_of_string(payload.locale)
        ];
}

var Payload = /* module */[
  /* from_t */from_t,
  /* to_t */to_t
];

export {
  locale_to_string ,
  locale_of_string ,
  Json ,
  Payload ,
  
}
/* No side effect */
