// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Http = require("http");
var Model$Reclock = require("../Model.bs.js");

var payload = /* record */[
  /* time */1,
  /* lang : En */0
];

function handler(_, res) {
  console.log("Sending you stuff...");
  res.write(Model$Reclock.Json[/* stringify */0](payload));
  res.end();
  console.log("Done! Yes!");
  return /* () */0;
}

Http.createServer(handler).listen(2112, (function () {
        console.log("Running...");
        return /* () */0;
      }));

exports.payload = payload;
exports.handler = handler;
/*  Not a pure module */
