// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
"use strict";

var Http = require("http");

Http.createServer(function(_, _$1) {
  return /* () */ 0;
}).listen(2112, function(prim) {
  console.log(prim);
  return /* () */ 0;
});

/*  Not a pure module */
