// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


function language_to_str(lang) {
  switch (lang) {
    case 0 : 
        return "En";
    case 1 : 
        return "De";
    case 2 : 
        return "Es";
    
  }
}

function t_to_jsT(t) {
  return {
          time: t[/* time */0],
          lang: language_to_str(t[/* lang */1])
        };
}

var foo = /* record */[
  /* time */1,
  /* lang : En */0
];

var bar = t_to_jsT(foo);

console.log(bar);

exports.language_to_str = language_to_str;
exports.t_to_jsT = t_to_jsT;
exports.foo = foo;
exports.bar = bar;
/* bar Not a pure module */
