// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


function language_to_str(lang) {
  switch (lang) {
    case 0 : 
        return "En";
    case 1 : 
        return "De";
    case 2 : 
        return "Es";
    
  }
}

function language_of_str(param) {
  switch (param) {
    case "DE" : 
        return /* De */1;
    case "ES" : 
        return /* Es */2;
    default:
      return /* En */0;
  }
}

function t_to_jsT(t) {
  return {
          time: t[/* time */0],
          lang: language_to_str(t[/* lang */1])
        };
}

function jsT_to_t(jsT) {
  return /* record */[
          /* time */jsT.time,
          /* lang */language_of_str(jsT.lang)
        ];
}

function stringify(t) {
  return JSON.stringify(t_to_jsT(t));
}

function parse(s) {
  return jsT_to_t(JSON.parse(s));
}

var Json = /* module */[
  /* stringify */stringify,
  /* parse */parse
];

function from_t(t) {
  return {
          time: t[/* time */0],
          lang: language_to_str(t[/* lang */1])
        };
}

function to_t(payload) {
  return /* record */[
          /* time */payload.time,
          /* lang */language_of_str(payload.lang)
        ];
}

var Payload = /* module */[
  /* from_t */from_t,
  /* to_t */to_t
];

exports.language_to_str = language_to_str;
exports.language_of_str = language_of_str;
exports.t_to_jsT = t_to_jsT;
exports.jsT_to_t = jsT_to_t;
exports.Json = Json;
exports.Payload = Payload;
/* No side effect */
