// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var App$Reclock = require("./App.bs.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Model$Reclock = require("../Model.bs.js");

var payload = /* record */[
  /* time */1,
  /* lang : En */0
];

console.log(Model$Reclock.Json[/* stringify */0](payload));

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, App$Reclock.make(/* array */[])), "app");

exports.payload = payload;
/*  Not a pure module */
