// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Component1$Reclock = require("./Component1.bs.js");
var Component2$Reclock = require("./Component2.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Component1$Reclock.make("Hello!", /* array */[])), "index1");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Component2$Reclock.make("Hello!", /* array */[])), "index2");

/*  Not a pure module */
